### ISSUE TITLE
Couldn't deserialize keys: Boot000f, Boot000b, Boot000a

### ISSUE THREAD

**Issue by stroodlepup** [Neverous/efibooteditor#30]
an error "Couldn't deserialize keys: Boot000f, Boot000b, Boot000a" appeared

![image](https://user-images.githubusercontent.com/1712880/176484723-cc00801c-3c77-4d67-aa89-4f9bfa7932f8.png)

**Comment by Neverous** [comment]
Is this with the latest version (v1.1.2)? Seems like it, just want to make sure as it should have a workaround for those now (at least the deserialization errors I've encountered - unsupported device path nodes), yeah I see the Unknown device path node in there  :thinking: 

Can you share the raw EFI dump (Help -> Dump raw EFI data)? It would alllow me to debug this locally. 

As I'm not sure if vendors are writing any private data (serial numbers of the machine or whatever) in the EFI variables, probably best to use email for that: neverous@neverous.info

**Comment by aureolebigben** [comment]
Hello, i have exactly the same problem. 
I think you could not deserialize Windows Boot Manager (because i did not see it in the list and i know Windows Boot Manager have exactly 3 EFI files).
![Screenshot_20220705_165731](https://user-images.githubusercontent.com/4173306/177357621-72dd631a-e75f-4de6-bda4-298cca3fa297.png)

I send you the dump by mail.

Have a nice day.

**Comment by Neverous** [comment]
Found the bug - basically It wasn't a problem with reading the entries data itself but with finding ones with index higher than 9 (as it was trying to read the wrong EFI variables because of case mismatch)... 

If you're building from git, master branch should work now, otherwise if you wait for the binaries I will probably do a bugfix release within a next few days.
